provider:
  host: https://idp.grash-cmms.com:9443
spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-name: WSO2 Identity Server
            client-id: A2UHKWNjFXnWrHGxupX22wgXBKka
            client-secret: GOttUrhyghii0Xum4OlHMMIZme8a
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          wso2:
            issuer-uri: https://idp.grash-cmms.com:9443/oauth2/token
            jwk-set-uri: https://idp.grash-cmms.com:9443/oauth2/jwks
            authorization-uri: https://idp.grash-cmms.com:9443/oauth2/authorize
            token-uri: https://idp.grash-cmms.com:9443/oauth2/token
            user-info-uri: https://idp.grash-cmms.com:9443/oauth2/userinfo
    thymeleaf:
      cache: false

  #    tomcat:
  #      max-wait: 20000
  #      max-active: 50
  #      max-idle: 20
  #      min-idle: 15
  servlet:
    multipart:
      max-request-size: 7MB
      max-file-size: 7MB
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        id:
          new_generator_mappings: false
    defer-datasource-initialization: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PWD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

server:
  port: 8080 # This is the default port anyway, but you can change it here
#  ssl:
#    enabled: true
#    key-alias: api
#    key-store: file:C:/Users/ambro/Desktop/sutura/api/src/main/resources/keystore/apikeystore.jks
#    key-store-type: JKS
#    key-store-password: password
#    key-password: password

security:
  jwt:
    token:
      secret-key: Grash4785@jk
      expire-length: 172800000 # 1000*60*60*24*2

frontend:
  url: http://localhost:3000
mail:
  recipient: #recipient@gmail.com
superAdmin:
  role:
    name: SuperAdministratorGrash@p;l
