provider:
  host: https://idp.grash-cmms.com:9443

client:
  client-id: 6SkR8P5Fd53bG5IfQiGvu9h9y9ka
  client-secret: dnYUG0u8AWm2b6fraEk0xef64vMa
  post-logout-uri: http://localhost:8080/login
  scope: openid
  authorization-grant-type: authorization_code
spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-name: WSO2 Identity Server
            client-id: ${client.client-id} #Change client-id
            client-secret: ${client.client-secret} # Change client-secret
            authorization-grant-type: ${client.authorization-grant-type}
            scope: ${client.scope}
        provider:
          wso2:
            issuer-uri: ${provider.host}/oauth2/token

  thymeleaf:
    cache: false

  #    tomcat:
  #      max-wait: 20000
  #      max-active: 50
  #      max-idle: 20
  #      min-idle: 15
  servlet:
    multipart:
      max-request-size: 7MB
      max-file-size: 7MB
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        id:
          new_generator_mappings: false
    defer-datasource-initialization: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PWD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

server:
  port: 8080 # This is the default port anyway, but you can change it here
#  ssl:
#    enabled: true
#    key-alias: api
#    key-store: file:C:/Users/ambro/Desktop/sutura/api/src/main/resources/keystore/apikeystore.jks
#    key-store-type: JKS
#    key-store-password: password
#    key-password: password

security:
  jwt:
    token:
      secret-key: Grash4785@jk
      expire-length: 172800000 # 1000*60*60*24*2

frontend:
  url: http://localhost:3000
api:
  url: http://localhost:8080
mail:
  recipient: #recipient@gmail.com
superAdmin:
  role:
    name: SuperAdministratorGrash@p;l
